name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        # https://github.com/actions/virtual-environments/tree/main/images/linux
        - { os: "ubuntu-20.04", cc: "gcc-10", cxx: "g++-10" }
        - { os: "ubuntu-20.04", cc: "clang-12", cxx: "clang++-12" }
        - { os: "ubuntu-22.04", cc: "gcc-12", cxx: "g++-12" }
        - { os: "ubuntu-22.04", cc: "clang-15", cxx: "clang++-15" }
    
    #name: "${{matrix.config.cxx}}"
    steps:
    - name: Setup
      run: |
        sudo apt-get update -o Acquire::Retries=10
        sudo apt-get install -o Acquire::Retries=10 -y cmake ninja-build ${{matrix.config.cc}} ${{matrix.config.cxx}}
        sudo apt-get install -y libglew-dev
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libudev-dev
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: |
        cmake --preset linux-${{matrix.config.cc}}
        cmake --build --preset linux-${{matrix.config.cc}}-release
    - name: Test
      run: |
        ctest --preset linux-${{matrix.config.cc}}-release --rerun-failed --output-on-failure
